//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiVietSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenceData
    {
        public int ID { get; set; }
        public string Licence { get; set; }
        public string IP_Active { get; set; }
        public Nullable<System.DateTime> Date_Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
