//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiVietSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSo
    {
        public int LoaiSoID { get; set; }
        public string TenLoaiSo { get; set; }
    }
}
