//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiVietSo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VietSoEntities1 : DbContext
    {
        public VietSoEntities1()
            : base("name=VietSoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StaffInfo> StaffInfoes { get; set; }
        public virtual DbSet<VnChinese> VnChinese { get; set; }
        public virtual DbSet<LicenceData> LicenceDatas { get; set; }
    }
}
