//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiVietSo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vietsoEntities : DbContext
    {
        public vietsoEntities()
            : base("name=vietsoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LicenceData> LicenceDatas { get; set; }
        public virtual DbSet<StaffInfo> StaffInfoes { get; set; }
        public virtual DbSet<VnChinese> VnChinese { get; set; }
        public virtual DbSet<ListLongSo> ListLongSoes { get; set; }
        public virtual DbSet<LoaiSo> LoaiSoes { get; set; }
        public virtual DbSet<ListLongSo_ChoDuyet> ListLongSo_ChoDuyet { get; set; }
        public virtual DbSet<LabelText> LabelTexts { get; set; }
    }
}
