//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppVietSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VnChinese
    {
        public int ID { get; set; }
        public string vn { get; set; }
        public string chinese { get; set; }
        public string reading { get; set; }
        public Nullable<int> used { get; set; }
        public string nguCanh { get; set; }
        public string UpdateDT { get; set; }
        public string syncTime { get; set; }
    }
}
